apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vmy109ijs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vmy109ijs-go 
  name: vmy109ijs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vmy109ijs-go 
